/*
 * 002Button_Interrupt.c
 *
 *  Created on: Apr 18, 2025
 *      Author: eldon
 */


#include <stdint.h>
#include "stm32f446xx.h"

int main(void){

	//INITIALIZE GPIOA LED OUTPUT PIN9
	GPIO_Init2(GPIOA, GPIO_PIN5, GPIO_MODE_OUTPUT, GPIO_NO_PULLUP_PULLDOWN, GPIO_HIGH_SPD, GPIO_OPTYPE_PUSHPULL, NONE);

	//INITIALIZE GPIOC BUTTON INPUT ALREADY HAS PULLUP RES IN PCB
	GPIO_Init2(GPIOC, GPIO_PIN13, GPIO_MODE_IT_FT, GPIO_NO_PULLUP_PULLDOWN, NONE, NONE, NONE);


	//IRQ Configurations

	//ENABLED IRQ_NUMBER_EXTI10_15 = IRQ 40, TO BE RECEIVED AND PROCESSED BY THE CPU
	GPIO_IRQInterruptConfig(IRQ_NUMBER_EXTI10_15, ENABLE);

	//SETS THE PRIORITY OF IRQ 40 TO HIGHEST PRIOTITY THE LESSER THE NUMBER THE HIGHER THE PRIORITY
	GPIO_IRQPriorityConfig(IRQ_NUMBER_EXTI10_15, 1);

	for(;;){

	}

	return 0;
}


void EXTI15_10_IRQHandler(){
	GPIO_IRQHandling(GPIO_PIN13);
	GPIO_ToggleOutputPin(GPIOA, GPIO_PIN5);

}
